from .agestam_1985 import agestam_1985_si_translation_pine_to_birch, agestam_1985_si_translation_spruce_to_birch
from .leijon_1979 import Leijon_Pine_to_Spruce, Leijon_Spruce_to_Pine
from .hagglund_1981_si_to_productivity import hagglund_1981_SI_to_productivity
